### ISSUE TITLE
[Suggestion]  Current spell cost display on hud.

### ISSUE THREAD

**Issue by ffuentesm** [Sarenor/Ars-Instrumentum#10]
Really nice to have the spell mana cost display on the book tooltips, but would be possible to also display it on the UI near the mana bar, like how the Total mana is displayed currently? 

Also, would be possible for the glyph cost to show up when making spells, or that is no possible due to how the mod is built? 
![image](https://user-images.githubusercontent.com/44974827/232173614-73585b6d-47ee-4d16-ad55-d7f902b0ec12.png)

**Comment by Sarenor** [comment]
That's about as implemented as it's going to get with the changes from Alex.
