### ISSUE TITLE
[1.20.1] Patchouli integration broke

### ISSUE THREAD

**Issue by border999** [Sarenor/Ars-Instrumentum#19]
got this on startup

> [21:01:03] [Worker-ResourceReload-10/ERROR] [patchouli/]: Failed to load book ars_creo:artificers_notes defined by mod ars_creo, skipping java.lang.IllegalArgumentException: Book ars_creo:artificers_notes has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.

>

**Comment by Sarenor** [comment]
That's Ars Creo, not Ars Instrumentum, I'm afraid.

**Comment by border999** [comment]
![Screenshot 2024-01-17 075542](https://github.com/Sarenor/Ars-Instrumentum/assets/11824584/bdd49cec-bb5c-41ef-8789-69d84ff189f4)

**Comment by border999** [comment]
apologizes, both mods had the same issue and were right next to each other in the log.

**Comment by border999** [comment]
I'll throw this in a new issue if this update goes unnoticed for a couple hours.

**Comment by Sarenor** [comment]
Huh. Good to know and thanks!

**Comment by Sarenor** [comment]
Fix should be publishing on CF right now
