### ISSUE TITLE
Mod isnt forced to be on both server and client

### ISSUE THREAD

**Issue by elpocoburrito** [Sarenor/Ars-Instrumentum#20]
Ars Instrumentum is improperly configured and basically doesnt verify it is actually on both the client and server, allowing a client that has the mod to join a server which doesn't.

The end result is that clients crash when they trigger a key press event, somewhat randomly but very quickly after joining.

I'm assuming thats just a tag / property that isnt properly setup in some forge config to tell the mod is required on both sides.

**Comment by Sarenor** [comment]
That's intentional, so people who must have mana numbers can, even when the server doesn't have the mod.
Just rebind the Armarium keys to unbound.
