### ISSUE TITLE
crash log as requested

### ISSUE THREAD

**Issue by Vadewolf** [Sarenor/Ars-Instrumentum#22]
[crash-2024-12-04_10.12.41-client.txt](https://github.com/user-attachments/files/18011343/crash-2024-12-04_10.12.41-client.txt)

hope this helps

**Comment by Sarenor** [comment]
Only in the sense that I'm pretty sure that the error won't appear when you load up just Ars and Instrumentum because something in your modlist changes how Geckolib works or otherwise interferes in the rendering pipeline.

**Comment by Vadewolf** [comment]
id love to know wat it is pls cause nothing makes sense

**Comment by Sarenor** [comment]
You didn't like the explanation we gave you last week. You're free to come up with your own, but right now, with the information we have, everything points to "this isn't because of Ars, be it Instrumetum, Noveau or Additions" but of a conflict with something else that's out of scope for us and me specifically.

**Comment by Sarenor** [comment]
Let me try once more:
If you put your wallet in the same spot every day, it's been there for years, you've found it there for years, 200.000 people you've told where to find it found it there (ok, stretching the analogy, anyways) and suddenly, after it's been working for literal years without a problem, the wallet isn't there.
Do you doubt yourself for having put the wallet in some other place even though you haven't changed your routine for months or do you look for a thief?

What I'm saying is that something in your modlist stole the texture file or broke the loading of it and I can't tell what.

**Comment by Vadewolf** [comment]
oh ok and i am sorry if i seem rude i wasnt trying to be

**Comment by Sarenor** [comment]
All good, you weren't rude, I just don't understand why you come back a week later with the same problem expecting a different answer.

**Comment by Vadewolf** [comment]
mostly caused ive been taking the week trying to figure out the cause on my end but no luck so was hoping maybe u or bailey or someone had something tho i did learn its something between the mods geckolib ars instrumentum and digimobs thats causing the bug but idk wat
